'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class AgendamentoResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WStock.Domain.AgendamentoResource", GetType(AgendamentoResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Informe a empresa..
        '''</summary>
        Public Shared ReadOnly Property VALIDA_EMPRESA() As String
            Get
                Return ResourceManager.GetString("VALIDA_EMPRESA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Informe a NFe..
        '''</summary>
        Public Shared ReadOnly Property VALIDA_NFE() As String
            Get
                Return ResourceManager.GetString("VALIDA_NFE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Informe a quantidade do pallet..
        '''</summary>
        Public Shared ReadOnly Property VALIDA_QTD_PALLET() As String
            Get
                Return ResourceManager.GetString("VALIDA_QTD_PALLET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Informe o tipo de agendamento..
        '''</summary>
        Public Shared ReadOnly Property VALIDA_TIPO_AGENDAMENTO() As String
            Get
                Return ResourceManager.GetString("VALIDA_TIPO_AGENDAMENTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Informe o tipo de carga..
        '''</summary>
        Public Shared ReadOnly Property VALIDA_TIPO_CARGA() As String
            Get
                Return ResourceManager.GetString("VALIDA_TIPO_CARGA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Informe o tipo de pallet..
        '''</summary>
        Public Shared ReadOnly Property VALIDA_TIPO_PALLET() As String
            Get
                Return ResourceManager.GetString("VALIDA_TIPO_PALLET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Informe o tipo de veículo..
        '''</summary>
        Public Shared ReadOnly Property VALIDA_TIPO_VEICULO() As String
            Get
                Return ResourceManager.GetString("VALIDA_TIPO_VEICULO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Informe o transportador..
        '''</summary>
        Public Shared ReadOnly Property VALIDA_TRANSPORTADOR() As String
            Get
                Return ResourceManager.GetString("VALIDA_TRANSPORTADOR", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
